name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi! We'd love your contribution, hope you like that, feel free to propose your ideas."
        pr-message: "We'll check it as soon as possible, thanks! Don't forget to test your code before create a pull request."
